server:
  port: 7080
spring:

  sleuth:
    sampler:
      probability: 1
    messaging:
      enabled: true
  redis:
    cluster:
      nodes: 172.20.35.64:8000,172.20.35.64:8001,172.20.35.64:8002
      max-redirects: 2
    lettuce:
      pool:
        max-wait: 1s
        max-active: 8
        min-idle: 1
        max-idle: 8
    timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

